// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ko'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * S​o​r​r​y​,​ ​t​h​i​s​ ​p​a​g​e​ ​d​o​e​s​ ​n​o​t​ ​s​e​e​m​ ​t​o​ ​e​x​i​s​t
	 */
	custom404: string
	/**
	 * 한​국​어
	 */
	changeLang: string
	nav: {
		/**
		 * P​r​o​g​r​a​m
		 */
		program: string
		/**
		 * S​p​o​n​s​o​r​s
		 */
		sponsors: string
		/**
		 * C​o​d​e​ ​O​f​ ​C​o​n​d​u​c​t
		 */
		coc: string
		/**
		 * S​c​o​l​a​r​s​h​i​p​ ​S​u​p​p​o​r​t
		 */
		scholarships: string
		/**
		 * C​o​n​t​a​c​t
		 */
		contact: string
	}
}

export type TranslationFunctions = {
	/**
	 * Sorry, this page does not seem to exist
	 */
	custom404: () => LocalizedString
	/**
	 * 한국어
	 */
	changeLang: () => LocalizedString
	nav: {
		/**
		 * Program
		 */
		program: () => LocalizedString
		/**
		 * Sponsors
		 */
		sponsors: () => LocalizedString
		/**
		 * Code Of Conduct
		 */
		coc: () => LocalizedString
		/**
		 * Scolarship Support
		 */
		scholarships: () => LocalizedString
		/**
		 * Contact
		 */
		contact: () => LocalizedString
	}
}

export type Formatters = {}
