export interface Sponsor {
  id: number;
  name: string;
  thumbnail?: string;
  youtube?: string;
  logo: string;
  link: string;
  service: string;
  description: string;
  detail: string;
  isShow: boolean;
}

export const SPONSORS: Record<"ko" | "en", Sponsor[]> = {
  ko: [
    {
      id: 1,
      name: "현대자동차",
      thumbnail: "/images/sponsors/platinum/thumbnail_hyundai.webp",
      logo: "/images/sponsors/platinum/logo_hyundai.png",
      link: "https://talent.hyundai.com/main/main.hc",
      service: "현대자동차",
      description: `Progress for Humanity 
    "우리는 인류를 위해 옳은 일을 하고자 존재합니다."
    완성차 사업의 글로벌 리더십을 기반으로 Smart Mobility Solution Provider로의 신속 전환을 추진합니다. 
    우리 모두의 이동을 위해 오늘도 혁신하는 현대자동차에 합류하세요.`,
      detail: `현대자동차그룹은 글로벌 완성차 시장에서 매년 경이로운 성장을 하고 있으며 Global Top 3라는 놀라운 성과를 달성하였습니다. 이러한 성과를 넘어 이제 Software Defined Vehicle이라는 새로운 도전을 통해 IT 전문 기업으로 도약하고자 합니다.
    \n 현대자동차그룹은 자동차와 IT 기술을 접목한 Mobility Service를 통해 고객에게 새로운 가치를 제공할 것이며, 앞으로 고객들은 Software를 통해 Hardware를 업그레이드할 수 있고, 더욱 안전하고 편리한 이동 경험을 제공받게 될 것입니다.
    \n 지금 현대자동차와 함께 여러분의 미래를 만들어가세요. Come Grow with Us!`,
      isShow: true,
    },
    {
      id: 2,
      name: "드림어스컴퍼니",
      thumbnail: "/images/sponsors/gold/thumbnail_flo.jpg",
      logo: "/images/sponsors/gold/logo_dreamus.jpg",
      link: "https://recruit.dreamuscompany.com/",
      service: "드림어스컴퍼니",
      description: `드림어스컴퍼니는 쓰면 쓸수록 나와 점점 닮아가는
    취향 기반의 뮤직 플랫폼 'FLO'를 중심으로
    '플랫폼 - 음원 유통 - 공연 - MD- 음악 디바이스' 등
    음악 생태계 전반을 아우르는 음악 콘텐츠 비즈니스 기업입니다.`,
      detail: `FLO는 AI 기술 기반 개인의 취향을 정의하고 표현할 수 있도록 돕는 뮤직 플랫폼으로, 취향을 반영한 개인화 홈 화면부터 개성을 표현할 수 있는 콘텐츠 창작 환경까지, FLO는 단 한 명을 위한 서비스를 고민합니다.
    이처럼 드림어스컴퍼니는 FLO와 함께 새롭고 다채로운 음악 콘텐츠가 가득한, 음악의 각 주체들이 꿈꾸는 세상을 만들어 나가고 있습니다.`,
      isShow: true,
    },
    {
      id: 3,
      name: "당근마켓",
      thumbnail: "/images/sponsors/gold/thumbnail_daangn.webp",
      logo: "/images/sponsors/gold/logo_daangn.png",
      link: "https://about.daangn.com/",
      service: "당근마켓",
      description: `당근마켓은 지역을 기반으로 온·오프라인 연결의 가치를 만드는 하이퍼로컬 기업입니다. 대한민국 전역을 넘어 일본, 미국, 캐나다까지 전 세계로 나아가며 전에 없던 지역 생활 커뮤니티를 만들어가고 있어요. 중고거래, 모임, 가게 홍보와 당근페이를 통한 결제까지, 이웃과 더 가까워지는 따뜻한 경험을 할 수 있도록 노력하고 있습니다.`,
      detail: `당근마켓은 지역을 기반으로 온·오프라인 연결의 가치를 만드는 하이퍼로컬 기업입니다. 대한민국 전역을 넘어 일본, 미국, 캐나다까지 전 세계로 나아가며 전에 없던 지역 생활 커뮤니티를 만들어가고 있어요. 중고거래, 모임, 가게 홍보와 당근페이를 통한 결제까지, 이웃과 더 가까워지는 따뜻한 경험을 할 수 있도록 노력하고 있습니다.`,
      isShow: true,
    },
    {
      id: 4,
      name: "메가존소프트",
      thumbnail: "/images/sponsors/gold/thumbnail_megazon.webp",
      logo: "/images/sponsors/gold/logo_megazon.png",
      link: "https://www.megazonesoft.com/googlecloud",
      service: "메가존소프트",
      description: `메가존소프트는 구글 클라우드 프리미어 파트너로서 10년 이상의 기업 IT 운영 경험과 노하우를 바탕으로 고객에게 완벽한 매니지드 서비스(Managed Service)를 제공합니다.`,
      detail: `메가존소프트는 2009년부터 한국 최초로 Google과의 파트너십을 체결하였으며, 프리미어 파트너 입니다. 또한 아시아 No.1 클라우드 서비스 관리 업체(MSP)로서 최다 클라우드 구축 경험을 보유하고 있으며, 고객의 클라우드 여정과 고객이 원하는 클라우드의 혁신을 위한 실현할 수 있도록 체계적인 서비스를 제공하고 있습니다.`,
      isShow: true,
    },
    {
      id: 5,
      name: "AB180",
      thumbnail: "/images/sponsors/bronze/thumbnail_ab180.webp",
      logo: "/images/sponsors/bronze/logo_airbridge.png",
      link: "https://www.airbridge.io/",
      service: "에어브릿지",
      description: `AB180(에이비일팔공)은 2015년 설립된 데이터 기반의 마테크 전문 회사로, 웹+앱 통합 광고 기여도를 측정 및 분석하는 Airbridge(에어브릿지), 마케팅 자동화 & CRM 솔루션 Braze, 고객 행동 분석 솔루션 Amplitude를 통해 국내외 약 300개 이상 고객사들의 디지털 성장을 돕고 있습니다.`,
      detail: `AB180이 자체 개발 및 공급하는 모바일 광고 성과 분석 솔루션인 Airbridge는, 매일 세계 각국에서 발생하는 10억개 넘는 이벤트 데이터, 1억 대의 디바이스, 100만 RPM을 바탕으로, 웹과 앱을 넘나드는 사용자의 유입을 정확히 파악하고, 광고 채널 및 캠페인별 성과를 측정할 수 있는 국내 유일의 웹+앱 통합 광고 성과 어트리뷰션 솔루션입니다.`,
      isShow: true,
    },
    {
      id: 6,
      name: "오누이(설탭)",
      thumbnail: "/images/sponsors/bronze/thumbnail_onuii.png",
      logo: "/images/sponsors/bronze/logo_onuii.png",
      link: "https://seoltab.com/index",
      service: "오누이(설탭)",
      description: `Za세대를 위한 태블릿 공부의 혁신,
    No.1 Personalized Education을 이끌어갈 종합 학습 플랫폼 '설탭'`,
      detail: `(주)오누이는 매년 놀라운 성장을 거듭, 누적 매출 700억이라는 경이로운 성과를 달성하고 있는 No.1 에듀테크 스타트업입니다. 태블릿 기반의  1:1 온라인 과외 서비스 <설탭>으로 전국의 학생과 선생님을 실시간으로 연결하고 있습니다.<설탭>은 국내 최다 학습・수업・매칭 데이터 및 디지털 컨텐츠를 기반으로 공부의 전 영역을 디지털화, 학습 진단부터 수업까지 모든 학생에게 개인맞춤형 교육을 제공하는 AI Study Super App으로 도약하고자 합니다.Maximize Everyone's Potential,
    No.1 Personalized Education Platform, 설탭!`,
      isShow: true,
    },
    {
      id: 7,
      name: "오픈업",
      thumbnail: "/images/sponsors/silver/logo_openup.webp",
      logo: "/images/sponsors/silver/logo_openup.webp",
      link: "https://www.oss.kr/open_up_intro",
      service: "오픈업",
      description: `오픈소스SW를 개발, 공유, 활용하기를 원하는 개발자, 기업, 정부 등을 체계적으로 지원하고, 수요(기업, 공공기관) 및 공급(개발자, 기업)의 선순환 구조를 이루어 오픈소스SW 활성화의 허브 역할을 수행합니다.`,
      detail: `정보통신산업진흥원은 2003년부터 공개SW 활성화 정책을 추진하여 2020 Open UP 센터를 개소하고, 공개SW 기업지원, 개발자 지원, 커뮤니티 지원, 공공 활용지원등 공개SW활성화지원사업을 지속하고 있습니다.`,
      isShow: false,
    },
    {
      id: 8,
      name: "Jetbrains",
      thumbnail: "",
      logo: "",
      link: "https://www.jetbrains.com",
      service: "Jetbrains",
      description: "",
      detail: "",
      isShow: false,
    },
    {
      id: 9,
      name: "GoldenRabbit",
      thumbnail: "",
      logo: "",
      link: "https://goldenrabbit.co.kr",
      service: "GoldenRabbit",
      description: "",
      detail: "",
      isShow: false,
    },
    {
      id: 10,
      name: "Hanbit",
      thumbnail: "",
      logo: "",
      link: "https://www.hanbit.co.kr",
      service: "Hanbit",
      description: "",
      detail: "",
      isShow: false,
    },
    {
      id: 11,
      name: "Decoding",
      thumbnail: "",
      logo: "",
      link: "https://www.decoding.co.kr",
      service: "Decoding",
      description: "",
      detail: "",
      isShow: false,
    },
    {
      id: 12,
      name: "Jpub",
      thumbnail: "",
      logo: "",
      link: "https://jpub.tistory.com",
      service: "Jpub",
      description: "",
      detail: "",
      isShow: false,
    },
    {
      id: 13,
      name: "GoogleForDevelopers",
      thumbnail: "",
      logo: "",
      link: "https://developers.google.com/",
      service: "",
      description: "",
      detail: "",
      isShow: false,
    },
    {
      id: 14,
      name: "Awskrug",
      thumbnail: "",
      logo: "",
      link: "https://awskrug.github.io/",
      service: "",
      description: "",
      detail: "",
      isShow: false,
    },
    {
      id: 15,
      name: "Modulabs",
      thumbnail: "",
      logo: "",
      link: "https://modulabs.co.kr/",
      service: "Modulabs",
      description: "",
      detail: "",
      isShow: false,
    },
  ],
  en: [
    {
      id: 1,
      name: "Hyundai Motor Company",
      thumbnail: "/images/sponsors/platinum/thumbnail_hyundai.webp",
      logo: "/images/sponsors/platinum/logo_hyundai.png",
      link: "https://talent.hyundai.com/main/main.hc",
      service: "Hyundai Motor Company",
      description: `Progress for Humanity   
    "We exist to do the right thing for humanity."
    Building on our global leadership in the automotive business, we are rapidly transforming into a Smart Mobility Solution Provider. 
    Join us as we innovate today to keep us all moving.`,
      detail: `Hyundai Motor Group has been experiencing phenomenal growth in the global automobile market and has achieved a remarkable ranking of Global Top 3. We are now taking on a new challenge, Software Defined Vehicle, to become an IT specialist.
    \Hyundai Motor Group will provide new value to customers through Mobility Service, which combines automotive and IT technologies, and customers will be able to upgrade their hardware through software, providing a safer and more convenient travel experience.
    \n Create your future with Hyundai today. Come Grow with Us!`,
      isShow: true,
    },
    {
      id: 2,
      name: "Dreamus Company",
      thumbnail: "/images/sponsors/gold/thumbnail_flo.jpg",
      logo: "/images/sponsors/gold/logo_dreamus.jpg",
      link: "https://recruit.dreamuscompany.com/",
      service: "Dreamus Company",
      description: `Dreamus Company centers on FLO, a personalized music platform that becomes more like you the more you use it.
    centered on the taste-based music platform 'FLO'.
    'Platform - Music Distribution - Performance - MD - Music Device' etc.
    It is a music content business company that covers the entire music ecosystem.`,
      detail: `FLO is a music platform that uses AI technology to help individuals define and express their tastes. From a personalized home screen that reflects their tastes to a content creation environment that allows them to express their individuality, FLO thinks of services for just one person.
    As such, Dreamus Company is working with FLO to create a world full of new and diverse music content that each musician dreams of.`,
      isShow: true,
    },
    {
      id: 3,
      name: "Danggeun Market (Karrot)",
      thumbnail: "/images/sponsors/gold/thumbnail_daangn.webp",
      logo: "/images/sponsors/gold/logo_daangn.png",
      link: "https://about.daangn.com/",
      service: "Danggeun Market (Karrot)",
      description: `Creating warmer neighborhoods that bring people closer together.
    In my neighborhood, 3 out of 5 neighbors are involved with Danggeun Market.`,
      detail: `Danggeun Market puts the spotlight on the value of neighborhoods.
    We're creating a community of local living like never before, starting with a thrift store with neighbors who live nearby.
    Neighbors can exchange real stories about their neighborhoods, and shop owners can hear the voices of their neighbors up close.
    From trading, gathering, promoting, and paying, we're connecting a variety of neighborhood experiences with Danggeun Market.`,
      isShow: true,
    },
    {
      id: 4,
      name: "Megazone Soft",
      thumbnail: "/images/sponsors/gold/thumbnail_megazon.webp",
      logo: "/images/sponsors/gold/logo_megazon.png",
      link: "https://www.megazonesoft.com/googlecloud",
      service: "Megazone Soft",
      description: `As a Google Cloud Premier Partner, MegaZoneSoft has more than 10 years of experience in enterprise IT operations and know-how to provide customers with complete Managed Services.`,
      detail: `Megazone Soft was the first company in Korea to partner with Google since 2009 and is a Premier Partner. As Asia's No. 1 Cloud Service Provider (MSP), we have the most cloud deployment experience and provide systematic services to help our customers realize their cloud journey and the transformation they want.`,
      isShow: true,
    },
    {
      id: 5,
      name: "AB180",
      thumbnail: "/images/sponsors/bronze/thumbnail_ab180.webp",
      logo: "/images/sponsors/bronze/logo_airbridge.png",
      link: "https://www.airbridge.io/",
      service: "Airbridge",
      description: `AB180, founded in 2015, is a data-driven martech company that helps more than 300 domestic and international clients grow digitally through Airbridge, a web+app integrated ad attribution measurement and analysis solution, Braze, a marketing automation & CRM solution, and Amplitude, a customer behavior analysis solution.`,
      detail: `Airbridge, a mobile ad performance analytics solution developed and supplied by AB180, is the only integrated web+app ad performance attribution solution in Korea that can pinpoint the flow of users across web and app, and measure performance by ad channel and campaign, based on data from over 1 billion events, 100 million devices, and 1 million RPMs from around the world every day.`,
      isShow: true,
    },
    {
      id: 6,
      name: "Onui (Seoltab)",
      thumbnail: "/images/sponsors/bronze/thumbnail_onuii.png",
      logo: "/images/sponsors/bronze/logo_onuii.png",
      link: "https://seoltab.com/index",
      service: "Seoltab",
      description: `Revolutionizing tablet learning for Gen Za,
    Setab, a comprehensive learning platform that will lead the way for No.1 Personalized Education`,
      detail: `Onui Ltd. is a No.1 edtech startup that has been growing remarkably every year, achieving a cumulative revenue of 70 billion won. We are connecting students and teachers across the country in real-time with our tablet-based 1:1 online tutoring service <Sultap>.Based on the largest amount of learning, teaching, and matching data and digital content in Korea, we aim to digitize all areas of study and become an AI Study Super App that provides personalized education to every student from learning diagnosis to lessons.Maximize Everyone's Potential,
    No.1 Personalized Education Platform, Setup!`,
      isShow: true,
    },
    {
      id: 7,
      name: "Open UP",
      thumbnail: "/images/sponsors/silver/logo_openup.webp",
      logo: "/images/sponsors/silver/logo_openup.webp",
      link: "https://www.oss.kr/open_up_intro",
      service: "Open UP",
      description: `We systematically support developers, enterprises, governments, etc. who want to develop, share, and utilize open source SW, and act as a hub for the revitalization of open source SW by creating a virtuous cycle of demand (enterprises, public institutions) and supply (developers, enterprises).`,
      detail: `Since 2003, the Korea Information and Communication Industry Promotion Agency has been promoting open SW activation policies, opening the 2020 Open UP Center and continuing open SW activation support projects such as open SW enterprise support, developer support, community support, and public utilization support.`,
      isShow: false,
    },
    {
      id: 8,
      name: "Jetbrains",
      thumbnail: "",
      logo: "",
      link: "https://www.jetbrains.com",
      service: "Jetbrains",
      description: "",
      detail: "",
      isShow: false,
    },
    {
      id: 9,
      name: "GoldenRabbit",
      thumbnail: "",
      logo: "",
      link: "https://goldenrabbit.co.kr",
      service: "GoldenRabbit",
      description: "",
      detail: "",
      isShow: false,
    },
    {
      id: 10,
      name: "Hanbit",
      thumbnail: "",
      logo: "",
      link: "https://www.hanbit.co.kr",
      service: "Hanbit",
      description: "",
      detail: "",
      isShow: false,
    },
    {
      id: 11,
      name: "Decoding",
      thumbnail: "",
      logo: "",
      link: "https://www.decoding.co.kr",
      service: "Decoding",
      description: "",
      detail: "",
      isShow: false,
    },
    {
      id: 12,
      name: "Jpub",
      thumbnail: "",
      logo: "",
      link: "https://jpub.tistory.com",
      service: "Jpub",
      description: "",
      detail: "",
      isShow: false,
    },
    {
      id: 13,
      name: "GoogleForDevelopers",
      thumbnail: "",
      logo: "",
      link: "https://developers.google.com/",
      service: "",
      description: "",
      detail: "",
      isShow: false,
    },
    {
      id: 14,
      name: "Awskrug",
      thumbnail: "",
      logo: "",
      link: "https://awskrug.github.io/",
      service: "",
      description: "",
      detail: "",
      isShow: false,
    },
    {
      id: 15,
      name: "Modulabs",
      thumbnail: "",
      logo: "",
      link: "https://modulabs.co.kr/",
      service: "Modulabs",
      description: "",
      detail: "",
      isShow: false,
    },
  ],
};
